name: attendease
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.14.3
  get: ^4.6.6
  path_provider: ^2.0.9
  intl: ^0.19.0
  shimmer: ^3.0.0
  google_fonts: any
  flutter_svg:
  file_picker: ^6.1.1
  flutter_screenutil: ^5.9.3
  hive_flutter: ^1.1.0
  rename_app: ^1.6.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/launcher/
    - assets/images/
    - assets/icons/

flutter_icons:
  image_path: "assets/launcher/launcher_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "assets/launcher/launcher_bg.png"
  adaptive_icon_foreground: "assets/launcher/launcher_fg.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/launcher/launcher_icon.png"
  windows:
    generate: true
    image_path: "assets/launcher/launcher_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/launcher/launcher_icon.png"

